"""empty message

Revision ID: 3141345ddcf5
Revises: c5f6b10a3429
Create Date: 2021-07-14 16:21:12.368313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3141345ddcf5'
down_revision = 'c5f6b10a3429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist_Genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=40), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Show',
    sa.Column('artistid', sa.Integer(), nullable=False),
    sa.Column('venueid', sa.Integer(), nullable=False),
    sa.Column('starttime', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['artistid'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venueid'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('artistid', 'venueid')
    )
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_newvenues', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seekind_description', sa.String(length=150), nullable=True))
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seekind_description')
    op.drop_column('Artist', 'seeking_newvenues')
    op.drop_column('Artist', 'website_link')
    op.drop_table('Show')
    op.drop_table('Artist_Genre')
    # ### end Alembic commands ###
