"""empty message

Revision ID: c5f6b10a3429
Revises: 2933aaebf80c
Create Date: 2021-07-14 13:32:32.511628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f6b10a3429'
down_revision = '2933aaebf80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Venue_Genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=40), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_newtalents', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seekind_description', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seekind_description')
    op.drop_column('Venue', 'seeking_newtalents')
    op.drop_column('Venue', 'website_link')
    op.drop_table('Venue_Genre')
    # ### end Alembic commands ###
