"""empty message

Revision ID: d161a6eb06bf
Revises: 3141345ddcf5
Create Date: 2021-07-15 19:28:48.250708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd161a6eb06bf'
down_revision = '3141345ddcf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=150), nullable=True))
    op.drop_column('Artist', 'seekind_description')
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=150), nullable=True))
    op.drop_column('Venue', 'seekind_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seekind_description', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking_description')
    op.add_column('Artist', sa.Column('seekind_description', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
